spring.application.name=bffGrocery
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
server.port=8080

rails.base-url=${RAILS_URL}
rails.login=${RAILS_LOGIN}
rails.password=${RAILS_PASSWORD}

jwt.secret=${JWT_SECRET}
jwt.expiration=900000
jwt.refresh-expiration=2592000000

admin.login=${ADMIN_LOGIN}
admin.password=${ADMIN_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=true
spring.sql.init.mode=never
